# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58a1d9d0fce8c978293841d0bb461773fa4b6f458be4361ba3acd88bcfc8dd4f398c89befb5926141a8b3eda5947f1305638512a071b834f6c6db470676a24d9

test:
  secret_key_base: 673202c90a3cd7fa2eee2782f283ae02fab546c773ce068350ec83db16d208e581916d8ca6534e999472c6efee2b88f38dd45627294ea0fae451b2d61fd448bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
